#!/bin/sh /etc/rc.common

START=96
STOP=10
PROG=/sbin/mqtt-ciotc

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command ${PROG}
	config_load mqtt-ciotc
	config_get private-cert mqtt-ciotc private-cert
	config_get root-cert mqtt-ciotc root-cert

	[ -n $private-cert ] && procd_append_param command --private-cert $private-cert
	[ -n $root-cert ] && procd_append_param command --root-cert $root-cert
	procd_set_param respawn
	procd_close_instance
}

stop_service()
{
	service_stop ${PROG}
}

reload_service() {
#	procd_send_signal wifilife # use SIGHUP
	stop
	start
}

service_triggers() {
        procd_add_reload_trigger "mqtt-ciotc"
}
