#!/bin/sh

[ "$INTERFACE" != "wan" ] && exit

local ip="$(ip a show $DEVICE | awk '/inet / {print $2; exit}')"
ip="${ip%%/*}"

[ -z "$ip" ] && exit

set_disabled() {
	local disabled
	local new_disabled=$1
	config_load firewall
	config_get disabled settings disabled 0
	[ $disabled -eq $new_disabled ] && return
	uci set firewall.settings.disabled="$1"
	uci commit firewall
	fw3 reload
}

test_ip() {
	if [ -n "$(echo $ip | grep -E '^(192\.168|10\.|172\.1[6789]\.|172\.2[0-9]\.|172\.3[01]\.)')" ]; then
		set_disabled 1
	else
		set_disabled 0
	fi
}
	

case "$(uci -q get netmode.setup.curmode)" in
                repeater*)
			test_ip
                ;;
esac
