#!/bin/sh

[ "$INTERFACE" != "wan" ] && exit

. /lib/functions/network.sh

network_get_ipaddr ip $INTERFACE

[ -z "$ip" ] && exit

toggle_firewall() {
	local section=$1
	local disable=$2
	config_get name "$1" name
	if [ "$name" == "wan" ]; then
		uci -q set firewall.settings.disabled=$disable
		if [ "$disable" == "1" ]; then
			uci -q set firewall.$section.input="ACCEPT"
		else
			uci -q set firewall.$section.input="REJECT"
		fi
		uci -q commit firewall
	fi
}

set_disabled() {
	config_load firewall
	config_foreach toggle_firewall zone $1
}

test_ip() {
	if [ -n "$(echo $ip | grep -E '^(192\.168|10\.|172\.1[6789]\.|172\.2[0-9]\.|172\.3[01]\.)')" ]; then
		# private IP
		set_disabled 1
	else
		# public IP
		set_disabled 0
		[ "$1" -eq "1" ] && {
			uci set netmode.setup.repeaterready=0
			uci commit netmode
			local pid="$(ps | grep wificontro[l] | awk '/repeater/ {print $1}')"
			[ "$pid" != "" ] && kill $pid
		}
	fi
}

case "$(uci -q get netmode.setup.curmode)" in
                repeater*) test_ip ;;
		*) [ "$(uci -q get netmode.setup.repeaterready)" == "1" ] && test_ip 1;;
esac

