#!/bin/sh /etc/rc.common

source /lib/functions/uci-defaults.sh

START=70
STOP=12

USE_PROCD=1
NAME=dectmngr
PROG=/usr/sbin/dectmngr
LOG_PATH=/var/log/dectmngr
DB_PATH=/etc/dect

# Ask dectmngr to exit nicely and wait for it to clean up, which is a slow process.
stop_and_wait_dectmngr() {
	pidof $NAME && killall -q $NAME

	pidof $NAME && sleep 2 # wait for the process to stop gracefully
	while pidof $NAME; do
		killall -q -9 $NAME 
		sleep 1
	done
}

start_service() {
	local rfpi=
	local opt_rfpi=
	test $(db get hw.board.hasDect) = "0" && return

	echo 1 > /sys/class/gpio/gpio14/value

	rfpi=$(db -q get hw.board.dect_rfpi)
	[ -n "$rfpi" -a ${#rfpi} -eq 14 ] && opt_rfpi="-rfpi $rfpi"

	procd_open_instance
	procd_set_param command $PROG -comname ttyH0 -log $LOG_PATH/dect-cmbs.log $opt_rfpi
	procd_set_param respawn 6 2 3
	procd_set_param term_timeout 20
	procd_set_param triggers asterisk
	procd_close_instance
}

stop_service() {
	test $(db get hw.board.hasDect) = "0" && return

	echo 0 > /sys/class/gpio/gpio14/value
	stop_and_wait_dectmngr
}

reload_service() {
	stop_and_wait_dectmngr
	start
}

service_triggers()
{
	procd_add_reload_trigger asterisk
}

boot() {
	echo 14 > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio14/direction

	[ ! -d $LOG_PATH ] && mkdir -p $LOG_PATH
	[ ! -d $DB_PATH ] && mkdir -p $DB_PATH
	start
}

