#!/bin/sh

[ "$(uci -q get obuspa.global.interface)" == "$INTERFACE" ] || exit 0

[ "$ACTION" = ifup -o "$ACTION" = ifupdate ] || exit 0
[ "$ACTION" = ifupdate -a -z "$IFUPDATE_ADDRESSES" -a -z "$IFUPDATE_DATA" ] && exit 0

/etc/init.d/obuspa reload

