#!/bin/sh /etc/rc.common

START=14
STOP=96

USE_PROCD=1

start_service() {
	procd_open_instance
	config_load owsd
	config_get enable ubusproxy enable
        procd_set_param command "/sbin/topologyd"

	if [ "$enable" ]
	then
		procd_append_param command --root
	fi

	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers()
{
	procd_add_reload_trigger topologyd
}

reload_service() {
	stop
	start
}
