#!/bin/sh /etc/rc.common

START=14
STOP=96

USE_PROCD=1

start_service() {
	procd_open_instance
	config_load topologyd 
	procd_set_param command "/sbin/topologyd"
	procd_append_param command --root
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers()
{
	procd_add_reload_trigger topologyd
}

reload_service() {
	stop
	start
}
