#!/bin/sh

. /lib/functions.sh

add_owsd_object_wifi() {
	local wifi=$(uci -q get owsd.ubusproxy.object | grep wifi*)
	if [ -z "$wifi" ]; then
		uci -q add_list owsd.ubusproxy.object="wifi*"
		uci commit owsd
	fi
}

add_owsd_object_wifi
