#!/bin/sh

. /lib/functions.sh

add_owsd_object_wifi() {
	uci -q del_list owsd.ubusproxy.object="router.system"
	uci -q del_list owsd.ubusproxy.object="wifix"
	uci -q del_list owsd.ubusproxy.object="wifi.*"
	uci -q add_list owsd.ubusproxy.object="router.system"
	uci -q add_list owsd.ubusproxy.object="wifix"
	uci -q add_list owsd.ubusproxy.object="wifi.*"
	uci commit owsd
}

add_dnsmasq_lease_hwmask() {
	local ubusx="$(uci -q get owsd.ubusproxy.enable)"
	if [ "$ubusx" == "1" ]; then
		uci -q set dhcp.@dnsmasq[0].lease_hwmask='0x000000'
		uci commit dhcp
	fi
}

add_firewall_mbid() {
	local ubusx="$(uci -q get owsd.ubusproxy.enable)"
	if [ -f /etc/firewall.mbid ]; then
		uci -q get firewall.mbid || {
				uci -q set firewall.mbid=include
				uci -q set firewall.mbid.path="/etc/firewall.mbid"
				uci -q set firewall.mbid.reload=1
				uci commit firewall
		}
	fi
}

add_ruleng_section() {
	uci -q add ruleng rule
	uci -q set ruleng.@rule[-1].recipe='/etc/ruleng/mbid.json'
	uci commit ruleng
}

add_owsd_object_wifi
add_dnsmasq_lease_hwmask
add_firewall_mbid
add_ruleng_section
