#!/bin/sh

. /lib/functions.sh

add_owsd_object_wifi() {
	local wifi=$(uci -q get owsd.ubusproxy.object | grep wifi*)
	if [ -z "$wifi" ]; then
		uci -q add_list owsd.ubusproxy.object="wifi*"
		uci commit owsd
	fi
}

add_dnsmasq_lease_hwmask() {
	local ubusx="$(uci -q get owsd.ubusproxy.enable)"
	if [ "$ubusx" == "1" ]; then
		uci -q set dhcp.@dnsmasq[0].lease_hwmask='0x000000'
		uci commit dhcp
	fi
}

add_firewall_mbid() {
	local ubusx="$(uci -q get owsd.ubusproxy.enable)"
	if [ -f /etc/firewall.mbid ]; then
		uci -q get firewall.mbid || {
				uci -q set firewall.mbid=include
				uci -q set firewall.mbid.path="/etc/firewall.mbid"
				uci -q set firewall.mbid.reload=1
				uci del_list firewall.mbid._access_w=root
				uci add_list firewall.mbid._access_w=root
				uci commit firewall
		}
	fi
}

add_ruleng_section() {
	local ubusx="$(uci -q get owsd.ubusproxy.enable)"
	if [ "$ubusx" == "1" ]; then
		uci -q add ruleng rule
		uci -q set ruleng.@rule[-1].recipe='/etc/ruleng/mbid.json'
		uci commit ruleng
	fi
}

add_owsd_object_wifi
add_dnsmasq_lease_hwmask
add_firewall_mbid
add_ruleng_section
