#!/bin/sh

. /lib/functions.sh

add_owsd_object_wifi() {
	local wifi=$(uci -q get owsd.ubusproxy.object | grep wifi*)
	if [ -z "$wifi" ]; then
		uci -q add_list owsd.ubusproxy.object="wifi*"
		uci commit owsd
	fi
}

add_dnsmasq_lease_hwmask() {
	local ubusx="$(uci -q get owsd.ubusproxy.enable)"
	if [ "$ubusx" == "1" ]; then
		uci -q set dhcp.@dnsmasq[0].lease_hwmask='0x000000'
		uci commit dhcp
	fi
}

add_owsd_object_wifi
add_dnsmasq_lease_hwmask
