#!/bin/sh /etc/rc.common

START=98
STOP=10

USE_PROCD=1
NAME=mcast

include /lib/network
include /lib/mcast

service_triggers() {
	procd_add_reload_trigger network $NAME
}

start_service() {
	if [ -f "/etc/config/mcast" ]; then
		configure_mcast
	fi

	procd_open_instance
	procd_set_param command "$PROG_EXE"
	procd_set_param respawn
	procd_close_instance
}

stop_service() {
	service_stop $PROG_EXE
}

reload_service() {
	stop
	start
}

