#!/bin/sh /etc/rc.common
#
# Start the rulengd
#

START=100
PID_FILE=/var/state/rulengd.pid

start() {
        start-stop-daemon -S -b -m -p $PID_FILE -x /usr/bin/rulengd -- -r ruleng
}

stop() {
        start-stop-daemon -K -p $PID_FILE
}

restart() {
        stop
        start
}
