#!/bin/sh /etc/rc.common
#
# Start the rulengd
#

START=99
STOP=01

USE_PROCD=1
NAME=rulengd

start_service() {
	procd_open_instance
	procd_set_param command "rulengd" -r ruleng
	procd_set_param respawn
	procd_close_instance
}

stop() {
	service_stop rulengd
}

service_triggers()
{
	procd_add_reload_trigger ruleng
}

reload_service() {
	stop
	start
}

