#!/bin/sh

# receive new client events
# and trigger wificontrol in --router mode for that client

. /usr/share/libubox/jshn.sh

local action ipaddr macaddr network

timed_check() {
	while true; do
		ubus call repeater get_creds '{"network":"'$network'","file":"/tmp/wificontrol.txt"}' >/dev/null
		wificontrol --router
		sleep $1
	done
}


timed_check 60 &

ubus listen client | \
while read event ; do
	#echo "netmode-client-detect got event: $event" >/dev/console
	json_load "$event"
	json_select client
	json_get_var action action
	[ "$action" == "connect" ] || continue
	json_get_var macaddr macaddr
	json_get_var ipaddr ipaddr
	json_get_var network netwrork "lan"

	if echo $macaddr | grep -i -e "^00:22:07" -e "^44:D4:37" -e "^02:0C:07" -e "^06:0C:07"; then
		echo "netmode-client-detect: a new Inteno device detected on '$network' network (MACAddr:$macaddr IPAddr:$ipaddr)" >/dev/console
		ubus call repeater get_creds '{"network":"'$network'","file":"/tmp/wificontrol.txt"}'
		/sbin/wificontrol --router --destination $ipaddr
	fi
done
