#!/bin/sh

. /usr/share/libubox/jshn.sh
. /lib/functions.sh
include /lib/qos

case "$1" in
	list)
		echo '{ "queue_stats": { "ifname":"String", "qid":"Integer" } }'

	;;
	call)
		case "$2" in
			queue_stats)
				read input;
				json_load "$input"
				json_get_var iface ifname
				json_get_var qid qid

				read_queue_stats $iface $qid
			;;
		esac
	;;
esac

