#!/bin/sh

. /usr/share/libubox/jshn.sh
. /lib/functions.sh
include /lib/qos

case "$1" in
	list)
		echo '{ "queue_stats": { "ifname":"string", "qid":"string" } }'

	;;
	call)
		case "$2" in
			queue_stats)
				read input;
				json_load "$input"
				json_get_var iface ifname
				json_get_var qid qid
				if [ -n "$iface" -a -n "$qid" ]; then
					get_eth_q_stats $iface $qid
				else
					get_queue_stats
				fi
			;;
		esac
	;;
esac

