#!/bin/sh /etc/rc.common

START=98
STOP=20

USE_PROCD=1

start_service() {
	config_load "mapcontroller"

	local enabled
	config_get_bool enabled controller enabled 1
	[ "$enabled" -eq 0 ] && return 1

	procd_open_instance
        procd_set_param command "/usr/sbin/mapcontroller" "-d"
	procd_set_param respawn
#	procd_set_param stdout 1
#	procd_set_param stderr 1
	procd_close_instance
}

service_triggers()
{
	procd_add_reload_trigger "ieee1905"
}

reload_service() {
	stop
	start
}
