#!/bin/sh

[ "$ACTION" = "ifup" -a "$(uci -q get network.$INTERFACE.is_lan)" != "1" ] || exit 0

config_load voice_client
config_get bindintf SIP bindintf

[ -n "$bindintf" -a "$INTERFACE" != "$bindintf" ] && exit 0

. /lib/functions/network.sh

if [ -n "$bindintf" ]; then
	network_get_ipaddr bindaddr "$bindintf"
	[ -z "$bindaddr" ] && network_get_ipaddr6 bindaddr "$bindintf"
fi

bindaddr="${bindaddr:-::}"
sed -i "s/bindaddr=.*/bindaddr=$bindaddr/g" /etc/asterisk/sip.conf
[ -e /var/run/asterisk/asterisk.ctl ] && asterisk -rx "sip reload"
