#!/bin/sh

. /lib/functions.sh

generate_igmp_global_params(){
	uci add mcast igmp
	uci rename mcast.@igmp[-1]="igmp"
	uci set mcast.@igmp[-1].max_membership="20"
	uci set mcast.@igmp[-1].max_msf="10"
	uci set mcast.@igmp[-1].qrv="2"
	uci set mcast.@igmp[-1].force_version="0"

	uci add mcast mld
	uci rename mcast.@mld[-1]="mld"
	uci set mcast.@mld[-1].mldv1_unsolicited_report_interval="10"
	uci set mcast.@mld[-1].mldv2_unsolicited_report_interval="1"
	uci set mcast.@mld[-1].qrv="2"
	uci set mcast.@mld[-1].force_version="0"

	uci commit mcast
}

generate_mcast_config(){

	up_itf="$(uci -q get network.wan.ifname)"

	uci add mcast proxy
	uci rename mcast.@proxy[-1]="igmp_proxy_1"
	uci set mcast.@proxy[-1].enable="1"
	uci set mcast.@proxy[-1].proto="igmp"
	uci set mcast.@proxy[-1].version="2"
	uci set mcast.@proxy[-1].robustness="2"
	uci set mcast.@proxy[-1].query_interval="125"
	uci set mcast.@proxy[-1].query_response_interval="100"
	uci set mcast.@proxy[-1].last_member_query_interval="10"
	uci set mcast.@proxy[-1].fast_leave="1"
	uci set mcast.@proxy[-1].snooping_mode="2"
	uci set mcast.@proxy[-1].lan_to_lan="0"
	uci add_list mcast.@proxy[-1].downstream_interface="br-lan"

	IFS=" "
	for itf in $up_itf; do
		uci add_list mcast.@proxy[-1].upstream_interface="$itf"
	done

	uci add_list mcast.@proxy[-1].filter="239.0.0.0/8"
	uci commit mcast
}

if [ -s "/etc/config/mcast" ]; then
	if uci -q get mcast.@proxy[0] >/dev/null; then
		# return if there is any valid content
		exit
	else
		rm -f /etc/config/mcast
	fi
fi
touch /etc/config/mcast

generate_igmp_global_params

generate_mcast_config
