#!/bin/sh /etc/rc.common

START=21
STOP=10

USE_PROCD=1
NAME=urlfilter
PROG=/usr/sbin/urlfilter

configure_firewall()
{
	iptables -w -L FORWARD|grep -iqE "NFQUEUE"
	if [ "$?" -ne 0 ]; then
		# setup netfilter queue 0, use queue bypass so that if no application is
		# listening to this queue then traffic is unaffected.
		iptables -w -I FORWARD 1 -p tcp --dport 80 -j NFQUEUE --queue-num 0 --queue-bypass
		iptables -w -I FORWARD 2 -p tcp --dport 443 -j NFQUEUE --queue-num 0 --queue-bypass
		iptables -w -I INPUT 1 -p udp --dport 53 -j NFQUEUE --queue-num 0 --queue-bypass
		iptables -w -I INPUT 2 -p udp --sport 53 -j NFQUEUE --queue-num 0 --queue-bypass

		# disable acceleration for https packet so that they can be read by urlfilter
		ebtables -A FORWARD -p ip --ip-protocol 6 --ip-destination-port 443 -j SKIPLOG
	fi
	ip6tables -w -L FORWARD|grep -iqE "NFQUEUE"
	if [ "$?" -ne 0 ]; then
		#ip6table rules
		ip6tables -w -I FORWARD 1 -p tcp --dport 80 -j NFQUEUE --queue-num 0 --queue-bypass
		ip6tables -w -I FORWARD 2 -p tcp --dport 443 -j NFQUEUE --queue-num 0 --queue-bypass
		ip6tables -w -I INPUT 1 -p udp --dport 53 -j NFQUEUE --queue-num 0 --queue-bypass
		ip6tables -w -I INPUT 2 -p udp --sport 53 -j NFQUEUE --queue-num 0 --queue-bypass
	fi

}

start_service() {
	if [ "$(uci -q get urlfilter.globals.enable)" == "1" ]; then
		procd_open_instance urlfilter
		procd_set_param command ${PROG}
		configure_firewall
		procd_set_param respawn
		procd_close_instance

		# Now flush the existing connections, otherwise,
		# URL filtering cannot be performed on already open sites.
		if [ -n "$(which conntrack)" ]; then
			sleep 5
			conntrack -F
		fi
	fi
}

stop_service() {
	iptables -w -L FORWARD|grep -iqE "NFQUEUE"
	if [ "$?" -eq 0 ]; then
		iptables -w -D FORWARD -p tcp --dport 80 -j NFQUEUE --queue-num 0 --queue-bypass
		iptables -w -D FORWARD -p tcp --dport 443 -j NFQUEUE --queue-num 0 --queue-bypass
		iptables -w -D INPUT -p udp --dport 53 -j NFQUEUE --queue-num 0 --queue-bypass
		iptables -w -D INPUT -p udp --sport 53 -j NFQUEUE --queue-num 0 --queue-bypass
		ebtables -D FORWARD -p ip --ip-protocol 6 --ip-destination-port 443 -j SKIPLOG
	fi
	ip6tables -w -L FORWARD|grep -iqE "NFQUEUE"
	if [ "$?" -eq 0 ]; then
		#ip6table rules
		ip6tables -w -D FORWARD -p tcp --dport 80 -j NFQUEUE --queue-num 0 --queue-bypass
		ip6tables -w -D FORWARD -p tcp --dport 443 -j NFQUEUE --queue-num 0 --queue-bypass
		ip6tables -w -D INPUT -p udp --dport 53 -j NFQUEUE --queue-num 0 --queue-bypass
		ip6tables -w -D INPUT -p udp --sport 53 -j NFQUEUE --queue-num 0 --queue-bypass
	fi
}
reload_service() {
	stop
	start
}


service_triggers() {
	procd_add_reload_trigger "urlfilter"
	procd_add_reload_trigger "firewall"
}
