#!/bin/sh /etc/rc.common

START=21
STOP=10

USE_PROCD=1
NAME=urlfilter
PROG=/usr/sbin/urlfilter

configure_firewall()
{
	iptables -L FORWARD|grep -iqE "NFQUEUE"
	if [ "$?" -ne 0 ]; then
		echo "Applying firewall rule to setup NFQUEUE on forward traffic for urlfiltering"
		iptables -I FORWARD 1 -p tcp --dport 80 -j NFQUEUE --queue-num 0
		iptables -I FORWARD 2 -p tcp --dport 443 -j NFQUEUE --queue-num 0
		iptables -I INPUT 1 -p udp --dport 53 -j NFQUEUE --queue-num 0
		iptables -I INPUT 2 -p udp --sport 53 -j NFQUEUE --queue-num 0
	fi
}

start_service() {
	if [ -f "/etc/config/urlfilter" ]; then
		procd_open_instance urlfilter
		procd_set_param command ${PROG}
		configure_firewall
		procd_set_param respawn
		procd_close_instance
	fi
}

stop_service() {
	pidof $NAME >/dev/null
        if [ "$?" -eq 0 ]; then
                pidof $NAME > /dev/null 2>&1 && killall -q $NAME
                pidof $NAME > /dev/null 2>&1
                while pidof $NAME > /dev/null 2>&1; do
                        killall -q -9 $NAME
                done
        fi

	iptables -L FORWARD|grep -iqE "NFQUEUE"
	if [ "$?" -eq 0 ]; then
		echo "Deleting firewall rule to setup NFQUEUE on forward traffic for urlfiltering"
		iptables -D FORWARD -p tcp --dport 80 -j NFQUEUE --queue-num 0
		iptables -D FORWARD -p tcp --dport 443 -j NFQUEUE --queue-num 0
		iptables -D INPUT -p udp --dport 53 -j NFQUEUE --queue-num 0
		iptables -D INPUT -p udp --sport 53 -j NFQUEUE --queue-num 0
	fi
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger "urlfilter"
	procd_add_reload_trigger "firewall"
}
