#!/bin/sh

TOPOLOGY_FILE="/tmp/topology_change"
WPS_FILE="/tmp/virtual_push_button"

handle_topology_change() {
	[ -f ${TOPOLOGY_FILE} ] && \
		touch ${TOPOLOGY_FILE}
}

handle_wps() {
	[ -f ${WPS_FILE} ] && \
		touch ${WPS_FILE}
}

case "$ACTION" in
	add|register)
		[ "wifibutton" == "$INTERFACE" -o "ecobutton" == "$INTERFACE" ] && {
			handle_wps
		}
		[ "wifi_2g" == "$INTERFACE" ] && {
			handle_wps
		}
		[ "wifi_5g" == "$INTERFACE" ] && {
			handle_wps
		}
		[ "wpsbutton" == "$INTERFACE" ] && {
			handle_wps
		}
		[ "wpscbutton" == "$INTERFACE" ] && {
			handle_topology_change
		}
        ;;
        remove|unregister)
        ;;
esac
