#!/bin/sh /etc/rc.common

START=99

send_log()
{
	nr=$(db get hw.board.serial_number)
	hw=$(db get hw.board.model_name)
	fam=$(db get hw.board.iopVerFam)
	sw=$(db get hw.board.iopVersion)
	server=$(/sbin/uci get system.crashlog.server)

	while true
	do
	    scp  -S /usr/sbin/logssh /proc/last_kmsg log@${server}:log/${fam}_${hw}_${sw}_${nr}
	    if [ $? == 0 ]
	    then
	       break;
	    fi
	    # wait for another minute then try again
	    sleep 60
	done
}

fill_in_default()
{
    /sbin/uci add system log
    /sbin/uci rename system.@log[-1]=crashlog
    /sbin/uci set system.crashlog.enable=no
    /sbin/uci set system.crashlog.server="crashlog.iopsys.eu"
    /sbin/uci commit
}

boot()
{
    # is crashlog enabled ?
    enable=$(/sbin/uci get system.crashlog.enable)
    case $enable in
	0|no|NO|false|FALSE)
	    exit 0
	    ;;
	"")
	    fill_in_default
	    exit 0
	    ;;
    esac

    # is this boot a result from a crash ?
    reason=$(cat /etc/boot_reason)
    case $reason in
	HW|WD)
	    send_log&
	    ;;
    esac
}
