#!/bin/sh /etc/rc.common

START=96
STOP=21

USE_PROCD=1

start_service() {
	procd_open_instance
        procd_set_param command "/usr/sbin/i1905d"
	procd_set_param respawn
#	procd_set_param stdout 1
#	procd_set_param stderr 1
	procd_close_instance
}

service_triggers()
{
	procd_add_reload_trigger "ieee1905"
}

reload_service() {
	stop
	start
}
