#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG=/usr/sbin/ieee1905

start_service() {
	procd_open_instance
	procd_set_param command ${PROG}
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	stop
	start
}

service_triggers()
{
	procd_add_config_trigger "config.change" "ieee1905" /etc/init.d/ieee1905 restart
}
