#!/bin/sh /etc/rc.common

START=97
USE_PROCD=1

. /lib/functions.sh
include /lib/network

configure_sfpports(){
	local port ifname pause speed
	name=$1
	config_get speed $name speed
	config_get ifname $name ifname
	config_get pause $name pause
	set_fiber_speed $ifname $speed
	set_port_pause $ifname $pause
}

start_service() {
	config_load ports
	config_foreach configure_sfpports sfpport
}

service_triggers() {
	procd_add_reload_trigger ports
}

