#!/bin/sh /etc/rc.common

START=95
STOP=10

USE_PROCD=1
PROG=/usr/sbin/wifimngr

start_service() {
	procd_open_instance
	procd_set_param command ${PROG}
	procd_set_param env LIBWIFI_DEBUG_LEVEL=3    #for debugging only
#	procd_set_param stderr 1                    #for debugging only
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
        stop
        start
}

service_triggers() {
	procd_add_reload_trigger "wireless"
}
