#!/bin/sh /etc/rc.common
#
# Copyright (C) 2009 OpenWrt.org
#

START=99

start() {
        for i in down reset up;do
            hciconfig hci0 $i
        done
        hcitool lewladd D0:39:72:B6:43:8A
        hcitool lewladd D0:39:72:B6:18:AA
       sleep 1
        /sbin/btle_alarm
}

stop() {
        hciconfig hci0 down
        killall -9 btle_alarm
}
