#!/bin/sh

if [ -e /proc/nvram ]; then
    . /lib/voice/broadcom.sh
elif [ -n $(which fw_printenv) ] && [ $(fw_printenv -n uboot_version | sed 's/..*\(INTEL\)..*/\1/') = 'INTEL' ]; then
    . /lib/voice/intel.sh
else
    echo 'Warning: Could not detect platform'
    echo 'Defaulting to Broadcom'
    . /lib/voice/broadcom.sh
fi

uci -q get voice_client.call_filter0 >/dev/null || {

uci -q batch <<-EOT
	add voice_client call_filter
	rename voice_client.@call_filter[-1]=call_filter0
	set voice_client.call_filter0.block_foreign=0
	set voice_client.call_filter0.block_special_rate=0
	set voice_client.call_filter0.block_outgoing=0
	set voice_client.call_filter0.block_incoming=0
	commit voice_client
EOT

}

uci -q get voice_client.RINGING_STATUS >/dev/null || {

uci -q batch <<-EOT
	add voice_client ringing_status
	rename voice_client.@ringing_status[-1]=RINGING_STATUS
	set voice_client.RINGING_STATUS.status=0
	set voice_client.RINGING_STATUS.enabled=0
	set voice_client.RINGING_STATUS.shouldring=1
	commit voice_client
EOT

}

# Default phone volume for Iopsys 4.
uci -q batch <<-EOT
	set voice_client.$(getLineName)0.txgain=4
	set voice_client.$(getLineName)0.rxgain=4
	set voice_client.$(getLineName)1.txgain=4
	set voice_client.$(getLineName)1.rxgain=4
	set voice_client.$(getLineName)2.txgain=4
	set voice_client.$(getLineName)2.rxgain=4
	set voice_client.$(getLineName)3.txgain=4
	set voice_client.$(getLineName)3.rxgain=4
	set voice_client.$(getLineName)4.txgain=4
	set voice_client.$(getLineName)4.rxgain=4
	set voice_client.$(getLineName)5.txgain=4
	set voice_client.$(getLineName)5.rxgain=4
	set voice_client.$(getLineName)6.txgain=4
	set voice_client.$(getLineName)6.rxgain=4
	set voice_client.$(getLineName)7.txgain=4
	set voice_client.$(getLineName)7.rxgain=4
	commit voice_client
EOT

uci -q batch <<-EOT
        delete firewall.sip
        set firewall.sip=include
        set firewall.sip.path=/etc/firewall.sip
        set firewall.sip.reload=1
	uci del_list firewall.sip._access_w="root"
	uci add_list firewall.sip._access_w="root"
        commit firewall
EOT

# If dtmfmode is set to the obsolete compatability change to auto
sed -i 's/dtmfmode\s*=\s*compatibility/dtmfmode=auto/' /etc/asterisk/sip.conf

if [ $(uci get voice_client.SIP.dtmfmode) == 'compatibility' ]; then
    uci set voice_client.SIP.dtmfmode='auto'
    uci commit
fi

exit 0
