#!/bin/sh /etc/rc.common
#
# Start the imonitor
#

START=99
STOP=01

USE_PROCD=1
NAME=imonitor

start_service() {
	procd_open_instance
	procd_set_param command "imonitor"
	procd_set_param stdout 1
        procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
}

stop() {
	service_stop imonitor
}

reload_service() {
	stop
	start
}

