#!/bin/sh

wan=$(db -q get hw.board.ethernetWanPort)

[ -z "$wan" ] && exit 1 # no configuration
[ "$PORT" != "$wan" ] && exit 0

update_bstas() {
	local section="$1"
	local action="$2"
	local ifname onboarded

	config_get ifname "$section" ifname
	config_get_bool onboarded "$section" onboarded 0

	[ "$onboarded" -eq 0 ] && return

	wpa_cli -i "$ifname" "$action" > /dev/null 2>&1
}

if [ "$LINK" = "up" ]; then
	touch /tmp/map.agent.bsta_global_disable
	config_load "mapagent"
	config_foreach update_bstas bk-iface disconnect
else
	rm -f /tmp/map.agent.bsta_global_disable
	config_load "mapagent"
	config_foreach update_bstas bk-iface reconnect
fi
