#!/bin/sh /etc/rc.common

START=10
USE_PROCD=1

. /usr/share/libubox/jshn.sh
. /lib/network/config.sh

local modedir=$(uci -q get netmode.setup.dir)
[ -n "$modedir" ] || modedir="/etc/netmodes"

get_device() {
	local PORT_NAMES=$(db get hw.board.ethernetPortNames)
	local PORT_ORDER=$(db get hw.board.ethernetPortOrder)
        local cnt=1
        local idx=0

	local pnum=$(echo $PORT_NAMES | wc -w)

	if [ $pnum -le 2 ]; then
		PORT_NAMES=$(echo $PORT_NAMES | sed 's/LAN/LAN1/g')
	fi

	# get index of interface name
	for i in $PORT_NAMES; do
		if [ "$i" == "$1" ]; then
			idx=$cnt
		fi
		cnt=$((cnt+1))
	done

        # get port name from index
	cnt=1
	for i in $PORT_ORDER; do
		if [ "$cnt" == "$idx" ]; then
			echo $i
		fi
		cnt=$((cnt+1))
	done
}

populate_netmodes() {
	[ -f /etc/config/netmode -a -d $modedir ] || return

	delete_netmode() {
		uci delete netmode.$1
	}

	config_load netmode

	config_foreach delete_netmode netmode
	uci commit netmode

	wan=$(get_device WAN)
	lan1=$(get_device LAN1)
	lan2=$(get_device LAN2)
	lan3=$(get_device LAN3)
	lan4=$(get_device LAN4)
	lan5=$(get_device LAN5)

	for file in $(find $modedir -type f); do
		conf="$(echo $file | cut -d'/' -f5)"
		if [ "$conf" == "network" ]; then
			grep -q "\$WAN" $file && sed -i "s/\$WAN/$wan/g" $file
			grep -q "\$LAN1" $file && sed -i "s/\$LAN1/$lan1/g" $file
			grep -q "\$LAN2" $file && sed -i "s/\$LAN2/$lan2/g" $file
			grep -q "\$LAN3" $file && sed -i "s/\$LAN3/$lan3/g" $file
			grep -q "\$LAN4" $file && sed -i "s/\$LAN4/$lan4/g" $file

			ifname="$(uci -q get $file.wan.ifname | sed 's/[ \t]*$//')"
			uci -q set $file.wan.ifname="$ifname"
			uci -q commit $file
		fi
	done

	local hardware=$(db get hw.board.hardware)
	local keys lang desc exp exclude
	for mode in $(ls $modedir); do

			case "$mode" in
				repeater*)
					wlctl -i wl1 ap >/dev/null 2>&1 || ifconfig rai0 2>/dev/null | grep -q rai0 || continue
				;;
			esac

			lang=""
			desc=""
			exp=""
			uci -q set netmode.$mode=netmode
			uci -q set netmode.$mode.conf=$mode
			json_load "$(cat $modedir/$mode/DETAILS)"

			if json_select excluded_boards; then
				exclude=0
				_i=1
				while json_get_var board $_i; do
					case "$hardware" in
						$board)
							uci -q delete netmode.$mode
							exclude=1
							break
						;;
					esac
					_i=$((_i+1))
				done
				json_select ..
				[ $exclude -eq 1 ] && continue
			fi

			if json_select acl; then
				_i=1
				while json_get_var user $_i; do
					uci add_list netmode.$mode._access_r="$user"
					_i=$((_i+1))
				done
				json_select ..
			fi

			json_select description
			json_get_keys keys
			for k in $keys; do
				json_get_keys lang $k
				lang=$(echo $lang | sed 's/^[ \t]*//;s/[ \t]*$//')
				json_select $k
				json_get_var desc $lang
				uci -q set netmode.$mode."desc_$lang"="$desc"
				[ "$lang" == "en" ] && uci -q set netmode.$mode."desc"="$desc"
				json_select ..
			done
			json_select ..

			json_select explanation
			json_get_keys keys
			for k in $keys; do
				json_get_keys lang $k
				lang=$(echo $lang | sed 's/^[ \t]*//;s/[ \t]*$//')
				json_select $k
				json_get_var exp $lang
				uci -q set netmode.$mode."exp_$lang"="$exp"
				[ "$lang" == "en" ] && uci -q set netmode.$mode."exp"="$exp"
				json_select ..
			done
			json_select ..

			json_get_var cred credentials
			uci -q set netmode.$mode.askcred="$cred"
			json_get_var ulb uplink_band
			uci -q set netmode.$mode.uplink_band="$ulb"
			json_get_var reboot reboot
			uci -q set netmode.$mode.reboot="$reboot"
	done

	config_get curmode setup curmode
	[ -d /etc/netmodes/$curmode ] || {
		[ "$(db -q get hw.board.hardware)" == "EX400" ] && uci -q set netmode.setup.curmode="routed_mtk" || uci -q set netmode.setup.curmode="routed_brcm"
	}

	uci commit netmode
}

switch_netmode() {
	[ -f /etc/config/netmode -a -d $modedir ] || return

	config_load netmode

	config_get curmode setup curmode
	config_get conf $curmode conf
	cp /etc/netmodes/$conf/* /etc/config/
	rm -f /etc/config/DETAILS
	sync
	local reboot=$(uci -q get netmode.$curmode.reboot)
	local askcred=$(uci -q get netmode.$curmode.askcred)
	if [ "$reboot" == "0" ]; then
		/etc/init.d/enviroment reload
		if [ "$askcred" == "1" -a -f /tmp/wifi_imported_credentials ]; then
			wifi import "$(cat /tmp/wifi_imported_credentials)"
			rm -f /tmp/wifi_imported_credentials
			ubus call network reload
			wifi reload nodat
			sleep 5
			ubus call router.network reload
		fi
	else
		reboot &
	fi
}

start_service() {
	populate_netmodes
}

reload_service() {
        switch_netmode

	# set default JUCI page to overview
	uci -q set juci.juci.homepage="overview"
	uci commit juci
}

service_triggers()
{
	procd_add_reload_trigger netmode
}

