#!/bin/sh /etc/rc.common

START=10
USE_PROCD=1

NETMODED="/sbin/netmoded"

. /lib/functions.sh
. /lib/functions/netmode.sh

start_netmoded() {
	procd_open_instance
	procd_set_param command $NETMODED

	procd_append_param command --verbose warning -i macaddr
	procd_set_param stdout 1
	procd_set_param stderr 1

	procd_set_param respawn
	procd_close_instance
}

start_service() {
	populate_netmodes

	start_netmoded
}

reload_service() {
        switch_netmode

	start_netmoded
}

service_triggers()
{
	procd_add_reload_trigger netmode
}

