#
# Copyright (C) 2006-2011 OpenWrt.org
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=iop
PKG_VERSION:=1.0
PKG_RELEASE:=0

include $(INCLUDE_DIR)/package.mk

define Package/iup
  SECTION:=net
  CATEGORY:=Network
  TITLE:=iop utilities
endef

define Package/iup/description
	This package contains Intenos Iop utilities
endef

define Build/Compile
	true
endef

define Package/iup/install
	true
endef

$(eval $(call BuildPackage,iop))
