#!/bin/sh /etc/rc.common

START=14
STOP=96

USE_PROCD=1
NAME=dongled

start_service() {
	procd_open_instance
	config_load mdmngr
	config_get debug mdmngr debug 0
	procd_set_param command "/sbin/mdmngr"

#	procd_append_param command --debug "$debug"
	if [ "$debug" -gt 0 ]
	then
		procd_append_param command --debug "$debug"
	fi
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers()
{
	procd_add_reload_trigger mdmngr
}

reload_service() {
	stop
	start
}
