#!/bin/sh /etc/rc.common

START=97
STOP=21

USE_PROCD=1

start_service() {
	procd_open_instance
        procd_set_param command "/usr/sbin/topologyd"
	procd_set_param respawn
#	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers()
{
	procd_add_reload_trigger "network"
}

reload_service() {
	procd_send_signal "topologyd"
}
