#!/bin/sh /etc/rc.common

START=14
STOP=96

USE_PROCD=1

start_service() {
	procd_open_instance
        procd_set_param command "/usr/sbin/topologyd"

	procd_set_param respawn
#	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers()
{
	procd_add_reload_trigger "ieee1905"
}

reload_service() {
	stop
	start
}
