#!/bin/sh /etc/rc.common

# Uncomment this if functions need to called inside /lib/qos
# include /lib/qos

START=21
STOP=90

USE_PROCD=1
NAME=qosmngr

. /lib/functions.sh
include /lib/qos

start_service() {
	# Call functions to configure QoS
	if [ -f "/etc/config/qos" ]; then
		configure_qos
	fi

	# procd_open_instance
	# start the daemon responsible for reading qos stats
	# procd_set_param command "/sbin/qosmngr"
	# procd_set_param respawn
	# procd_close_instance
}

stop() {
	#stop_service() is called after procd killed the service
	echo ;
}

service_triggers() {
	procd_add_reload_trigger qos
}

reload_service() {
	# Call functions to configure QoS
	start
	
	# reload the daemon responsible for reading qos stats
	# ubus -t 5 call qos reload
}


