#!/bin/sh /etc/rc.common

# Uncomment this if functions need to called inside /lib/qos
# include /lib/qos

START=21

USE_PROCD=1
NAME=qosmngr

. /lib/functions.sh
include /lib/qos

start_service() {
	if [ -f "/etc/config/qos" ]; then
		ubus -S call qos reload
	fi

}

stop() {
	#stop_service() is called after procd killed the service
	echo ;
}

boot() {
	setup_qos
	start
}

service_triggers() {
	procd_add_reload_trigger qos
}

reload_service() {
	# Call functions to configure QoS
	start
}

restart() {
	setup_qos
	start
}
